package com.khadamati.app.ui.navigation

object Routes {
    const val SPLASH = "splash"
    const val LOGIN = "login"
    const val REGISTER = "register"
    const val FORGOT_PASSWORD = "forgot-password"
    const val RESET_PASSWORD = "reset-password"
    const val HOME = "home"
    const val SERVICES = "services"
    const val PROFILE = "profile"
    const val BOOKINGS = "bookings"
    const val BOOKING_DETAIL = "booking/{bookingId}"
    const val BOOKING_WIZARD = "booking-wizard"
    const val BOOKING_WIZARD_WITH_SERVICE = "booking-wizard/{serviceId}"
    const val NOTIFICATIONS = "notifications"
    const val SUBSCRIPTION_PLANS = "subscriptions"
    const val SUBSCRIBE = "subscriptions/{planId}"
    const val MY_SUBSCRIPTION = "subscription"
    const val ADDRESSES = "addresses"
    const val CHAT_LIST = "chat"
    const val BOOKING_CHAT = "booking/{bookingId}/chat"
    const val SUPPORT = "support"
    const val PROFILE_EDIT = "profile/edit"
    const val CRAFTSMAN_PORTAL = "craftsman-portal"
    const val STORE_PORTAL = "store-portal"
}
